spring:
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: geoke2021@gmail.com
    password: qkcbikkkqrouryia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true